// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"sync"
)

var (
	lockUserRepoMockAddUser sync.RWMutex
	lockUserRepoMockDelete  sync.RWMutex
	lockUserRepoMockGetUser sync.RWMutex
	lockUserRepoMockUpdate  sync.RWMutex
)

// UserRepoMock is a mock implementation of UserRepo.
//
//     func TestSomethingThatUsesUserRepo(t *testing.T) {
//
//         // make and configure a mocked UserRepo
//         mockedUserRepo := &UserRepoMock{
//             AddUserFunc: func(u *User) (string, error) {
// 	               panic("TODO: mock out the AddUser method")
//             },
//             DeleteFunc: func(id string) error {
// 	               panic("TODO: mock out the Delete method")
//             },
//             GetUserFunc: func(id string) (*User, error) {
// 	               panic("TODO: mock out the GetUser method")
//             },
//             UpdateFunc: func(u *User) error {
// 	               panic("TODO: mock out the Update method")
//             },
//         }
//
//         // TODO: use mockedUserRepo in code that requires UserRepo
//         //       and then make assertions.
//
//     }
type UserRepoMock struct {
	// AddUserFunc mocks the AddUser method.
	AddUserFunc func(u *User) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(id string) (*User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(u *User) error

	// calls tracks calls to the methods.
	calls struct {
		// AddUser holds details about calls to the AddUser method.
		AddUser []struct {
			// U is the u argument value.
			U *User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// ID is the id argument value.
			ID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// U is the u argument value.
			U *User
		}
	}
}

// AddUser calls AddUserFunc.
func (mock *UserRepoMock) AddUser(u *User) (string, error) {
	if mock.AddUserFunc == nil {
		panic("UserRepoMock.AddUserFunc: method is nil but UserRepo.AddUser was just called")
	}
	callInfo := struct {
		U *User
	}{
		U: u,
	}
	lockUserRepoMockAddUser.Lock()
	mock.calls.AddUser = append(mock.calls.AddUser, callInfo)
	lockUserRepoMockAddUser.Unlock()
	return mock.AddUserFunc(u)
}

// AddUserCalls gets all the calls that were made to AddUser.
// Check the length with:
//     len(mockedUserRepo.AddUserCalls())
func (mock *UserRepoMock) AddUserCalls() []struct {
	U *User
} {
	var calls []struct {
		U *User
	}
	lockUserRepoMockAddUser.RLock()
	calls = mock.calls.AddUser
	lockUserRepoMockAddUser.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepoMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("UserRepoMock.DeleteFunc: method is nil but UserRepo.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockUserRepoMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockUserRepoMockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedUserRepo.DeleteCalls())
func (mock *UserRepoMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockUserRepoMockDelete.RLock()
	calls = mock.calls.Delete
	lockUserRepoMockDelete.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *UserRepoMock) GetUser(id string) (*User, error) {
	if mock.GetUserFunc == nil {
		panic("UserRepoMock.GetUserFunc: method is nil but UserRepo.GetUser was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockUserRepoMockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	lockUserRepoMockGetUser.Unlock()
	return mock.GetUserFunc(id)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//     len(mockedUserRepo.GetUserCalls())
func (mock *UserRepoMock) GetUserCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockUserRepoMockGetUser.RLock()
	calls = mock.calls.GetUser
	lockUserRepoMockGetUser.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepoMock) Update(u *User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepoMock.UpdateFunc: method is nil but UserRepo.Update was just called")
	}
	callInfo := struct {
		U *User
	}{
		U: u,
	}
	lockUserRepoMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockUserRepoMockUpdate.Unlock()
	return mock.UpdateFunc(u)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedUserRepo.UpdateCalls())
func (mock *UserRepoMock) UpdateCalls() []struct {
	U *User
} {
	var calls []struct {
		U *User
	}
	lockUserRepoMockUpdate.RLock()
	calls = mock.calls.Update
	lockUserRepoMockUpdate.RUnlock()
	return calls
}
